
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 26 11:55:06 CST 2021
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 7;
  public static final int Parentesis_c = 16;
  public static final int Parentesis_a = 15;
  public static final int Numero = 26;
  public static final int Float = 4;
  public static final int True = 11;
  public static final int ERROR = 29;
  public static final int Flotante = 27;
  public static final int Identificador = 22;
  public static final int Int = 3;
  public static final int Llave_c = 19;
  public static final int False = 12;
  public static final int Coma = 28;
  public static final int Op_aritmetico = 23;
  public static final int Inicio = 20;
  public static final int Llave_a = 18;
  public static final int Op_relacional = 14;
  public static final int P_coma = 21;
  public static final int Cadena = 5;
  public static final int EOF = 0;
  public static final int If = 6;
  public static final int Return = 9;
  public static final int error = 1;
  public static final int Op_logico = 30;
  public static final int Escritura = 25;
  public static final int Class = 31;
  public static final int Lectura = 24;
  public static final int Void = 32;
  public static final int Igual = 13;
  public static final int While = 8;
  public static final int String = 2;
  public static final int Metodo = 17;
  public static final int Boolean = 10;
}

