/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import analisis.Main;

/**
 *
 * @author Kevin_Sanchez
 */
public class PnlAnalisis extends javax.swing.JPanel {

    /**
     * Creates new form pnlAnalisis
     */
    public PnlAnalisis() {
        initComponents();
        txtAreaLexico.setForeground(Main.lexicoColor);
        txtAreaSintactico.setForeground(Main.sintacticoColor);
        txtAreaSemantico.setForeground(Main.semanticoColor);
        txtAreaIntermedio.setForeground(Main.intermedioColor);
        txtAreaLexico.setText(Main.ResAnalisiLexico);
        txtAreaSintactico.setText(Main.ResAnalisiSintactico);
        txtAreaSemantico.setText(Main.ResAnalisiSemantico);
        txtAreaIntermedio.setText(Main.ResCodigoIntermedio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSemantico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaLexico = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaSintactico = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaIntermedio = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(162, 217, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaSemantico.setColumns(20);
        txtAreaSemantico.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtAreaSemantico.setRows(5);
        txtAreaSemantico.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(txtAreaSemantico);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 54, 661, 280));

        txtAreaLexico.setColumns(20);
        txtAreaLexico.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtAreaLexico.setRows(5);
        txtAreaLexico.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane2.setViewportView(txtAreaLexico);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 676, 280));

        txtAreaSintactico.setColumns(20);
        txtAreaSintactico.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtAreaSintactico.setRows(5);
        txtAreaSintactico.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane3.setViewportView(txtAreaSintactico);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 383, 676, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Código intermedio");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 340, 660, 37));

        txtAreaIntermedio.setColumns(20);
        txtAreaIntermedio.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtAreaIntermedio.setRows(5);
        txtAreaIntermedio.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane4.setViewportView(txtAreaIntermedio);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 383, 660, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ánalisis léxico");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 676, 34));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ánalisis sintactico");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 676, 37));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ánalisis semantico");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 11, 660, 37));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextArea txtAreaIntermedio;
    public static javax.swing.JTextArea txtAreaLexico;
    public static javax.swing.JTextArea txtAreaSemantico;
    public static javax.swing.JTextArea txtAreaSintactico;
    // End of variables declaration//GEN-END:variables
}
