/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import analisis.Main;
import javax.swing.JViewport;
import jsyntaxpane.DefaultSyntaxKit;

/**
 *
 * @author Kevin_Sanchez
 */
public class PnlCodigoOptimizado extends javax.swing.JPanel {

    /**
     * Creates new form pnlCodigoOptimizado
     */
    public PnlCodigoOptimizado() {
        initComponents();
        DefaultSyntaxKit.initKit();
        optimizado.setContentType("text/java");
        fuente.setContentType("text/java");
        fuente.setText(Main.ResCodigoFuente);
        optimizado.setText(Main.ResCodigoOptimizado);
        txtCodigoFuente.setText(Main.ResFuente);
        txtCodigoOptimizado.setText(Main.ResOptimizacion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        txtCodigoFuente = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCodigoOptimizado = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        fuente = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        optimizado = new javax.swing.JEditorPane();
        rSButton1 = new rojeru_san.RSButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(162, 217, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoFuente.setColumns(20);
        txtCodigoFuente.setRows(5);
        jScrollPane3.setViewportView(txtCodigoFuente);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 680, -1));

        txtCodigoOptimizado.setColumns(20);
        txtCodigoOptimizado.setRows(5);
        jScrollPane4.setViewportView(txtCodigoOptimizado);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 680, -1));

        jScrollPane1.setViewportView(fuente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 680, 500));

        jScrollPane2.setViewportView(optimizado);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 680, 500));

        rSButton1.setText("Reemplazar");
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });
        add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 130, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Codigo optimizado");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 680, 34));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Código fuente");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 676, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed

        if (VtnCompilador.tabEdicion.getTabCount() != 0) {
            
            int index = VtnCompilador.tabEdicion.getSelectedIndex();
            String s = VtnCompilador.tabEdicion.getTitleAt(index);
            javax.swing.JScrollPane scroll = (javax.swing.JScrollPane) VtnCompilador.tabEdicion.getComponentAt(index);
            JViewport view = scroll.getViewport();
            javax.swing.JEditorPane edit = (javax.swing.JEditorPane) view.getView();
            edit.setText(Main.ResCodigoOptimizado);
            Main.textoFuente = Main.ResCodigoOptimizado;
        }
    }//GEN-LAST:event_rSButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JEditorPane fuente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JEditorPane optimizado;
    private rojeru_san.RSButton rSButton1;
    public static javax.swing.JTextArea txtCodigoFuente;
    public static javax.swing.JTextArea txtCodigoOptimizado;
    // End of variables declaration//GEN-END:variables
}
