/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import analisis.Main;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JTextPane;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;
import jsyntaxpane.DefaultSyntaxKit;
import recursos.*;

/**
 *
 * @author Kevin_Sanchez
 */
public class VtnCompilador extends javax.swing.JFrame {

    public static ImageIcon imageLenguaje1 = new ImageIcon(ClassLoader.getSystemResource("imagenes/edicion.png"));
    public static ImageIcon imageLenguaje2 = new ImageIcon(ClassLoader.getSystemResource("imagenes/salida.png"));

    /**
     * Creates new form VtnCompilador
     */
    public VtnCompilador() {
        initComponents();
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/proyecto.png"));
        this.setIconImage(icono);
        setTitle("Compilador");
        setLocationRelativeTo(null);

        TabbedPaneUI blackTabbedPaneUI = new TabbedPaneUI();
        tabEdicion.setUI(blackTabbedPaneUI);
        DefaultSyntaxKit.initKit();
        DefaultSyntaxKit.initKit();
        javax.swing.JScrollPane scrollPag = new javax.swing.JScrollPane();
        JEditorPane pag = new JEditorPane();
        scrollPag.setViewportView(pag);
        pag.setContentType("text/java");
        tabEdicion.addTab("Edición", scrollPag);
        CmpntTabPane pnlTab = new CmpntTabPane(tabEdicion, 0, VtnCompilador.imageLenguaje1);
        tabEdicion.setTabComponentAt(tabEdicion.getTabCount() - 1, pnlTab);
        tabEdicion.setTabComponentAt(0, pnlTab);
        //Salida
        TabbedPaneUI blackTabbedPaneUI2 = new TabbedPaneUI();
        tabSalida.setUI(blackTabbedPaneUI2);
        CmpntTabPane panelTab2 = new CmpntTabPane(tabSalida, -1, imageLenguaje2);
        tabSalida.setTabComponentAt(0, panelTab2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelNavegacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        btnDocumentacion = new rojeru_san.RSButton();
        btnNuevo = new rojeru_san.RSButton();
        btnGuardar = new rojeru_san.RSButton();
        btnLimpiar = new rojeru_san.RSButton();
        btnCompilar = new rojeru_san.RSButton();
        btnLexico = new rojeru_san.RSButton();
        btnSintactico = new rojeru_san.RSButton();
        btnSemantico = new rojeru_san.RSButton();
        btnIntermedio = new rojeru_san.RSButton();
        btnOptimizado = new rojeru_san.RSButton();
        btnAbrir = new rojeru_san.RSButton();
        btnObjeto = new rojeru_san.RSButton();
        btnAcerca = new rojeru_san.RSButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        tabEdicion = new javax.swing.JTabbedPane();
        tabSalida = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        editorPaneSalida = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador");
        setBackground(new java.awt.Color(255, 255, 255));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1430, 900));

        panelNavegacion.setBackground(new java.awt.Color(162, 217, 245));
        panelNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Compilador");
        panelNavegacion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 180, 37));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proyecto (3).png"))); // NOI18N
        panelNavegacion.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 70, 80));

        btnDocumentacion.setBackground(new java.awt.Color(162, 217, 245));
        btnDocumentacion.setForeground(new java.awt.Color(0, 102, 102));
        btnDocumentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-50-notebook.png"))); // NOI18N
        btnDocumentacion.setText("Documentación");
        btnDocumentacion.setColorHover(new java.awt.Color(255, 255, 255));
        btnDocumentacion.setColorText(new java.awt.Color(0, 51, 102));
        btnDocumentacion.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnDocumentacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDocumentacion.setIconTextGap(15);
        btnDocumentacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-50-notebook (3).png"))); // NOI18N
        btnDocumentacion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-50-notebook.png"))); // NOI18N
        btnDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentacionActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnDocumentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 290, -1));

        btnNuevo.setBackground(new java.awt.Color(162, 217, 245));
        btnNuevo.setForeground(new java.awt.Color(0, 102, 102));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-55-document-text.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setColorHover(new java.awt.Color(255, 255, 255));
        btnNuevo.setColorText(new java.awt.Color(0, 51, 102));
        btnNuevo.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnNuevo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNuevo.setIconTextGap(15);
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-55-document-text (3).png"))); // NOI18N
        btnNuevo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-55-document-text.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, -1));

        btnGuardar.setBackground(new java.awt.Color(162, 217, 245));
        btnGuardar.setForeground(new java.awt.Color(0, 102, 102));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-57-document-download.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setColorHover(new java.awt.Color(255, 255, 255));
        btnGuardar.setColorText(new java.awt.Color(0, 51, 102));
        btnGuardar.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGuardar.setIconTextGap(15);
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-57-document-download (3).png"))); // NOI18N
        btnGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-57-document-download.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, -1));

        btnLimpiar.setBackground(new java.awt.Color(162, 217, 245));
        btnLimpiar.setForeground(new java.awt.Color(0, 102, 102));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-126-document-shred.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setColorHover(new java.awt.Color(255, 255, 255));
        btnLimpiar.setColorText(new java.awt.Color(0, 51, 102));
        btnLimpiar.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimpiar.setIconTextGap(15);
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-126-document-shred (3).png"))); // NOI18N
        btnLimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-126-document-shred.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, -1));

        btnCompilar.setBackground(new java.awt.Color(162, 217, 245));
        btnCompilar.setForeground(new java.awt.Color(0, 102, 102));
        btnCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-66-document-play.png"))); // NOI18N
        btnCompilar.setText("Compilar");
        btnCompilar.setColorHover(new java.awt.Color(255, 255, 255));
        btnCompilar.setColorText(new java.awt.Color(0, 51, 102));
        btnCompilar.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnCompilar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCompilar.setIconTextGap(15);
        btnCompilar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-66-document-play (3).png"))); // NOI18N
        btnCompilar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-66-document-play.png"))); // NOI18N
        btnCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnCompilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, -1));

        btnLexico.setBackground(new java.awt.Color(162, 217, 245));
        btnLexico.setForeground(new java.awt.Color(0, 102, 102));
        btnLexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-87-document-font.png"))); // NOI18N
        btnLexico.setText("Ánalisis léxico");
        btnLexico.setColorHover(new java.awt.Color(255, 255, 255));
        btnLexico.setColorText(new java.awt.Color(0, 51, 102));
        btnLexico.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnLexico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLexico.setIconTextGap(15);
        btnLexico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-87-document-font (3).png"))); // NOI18N
        btnLexico.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-87-document-font.png"))); // NOI18N
        btnLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexicoActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnLexico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 290, -1));

        btnSintactico.setBackground(new java.awt.Color(162, 217, 245));
        btnSintactico.setForeground(new java.awt.Color(0, 102, 102));
        btnSintactico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-69-document-text.png"))); // NOI18N
        btnSintactico.setText("Ánalisis sintactico");
        btnSintactico.setColorHover(new java.awt.Color(255, 255, 255));
        btnSintactico.setColorText(new java.awt.Color(0, 51, 102));
        btnSintactico.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnSintactico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSintactico.setIconTextGap(15);
        btnSintactico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-69-document-text (3).png"))); // NOI18N
        btnSintactico.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-69-document-text.png"))); // NOI18N
        btnSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSintacticoActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnSintactico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, -1));

        btnSemantico.setBackground(new java.awt.Color(162, 217, 245));
        btnSemantico.setForeground(new java.awt.Color(0, 102, 102));
        btnSemantico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-86-document-list.png"))); // NOI18N
        btnSemantico.setText("Ánalisis semantico");
        btnSemantico.setColorHover(new java.awt.Color(255, 255, 255));
        btnSemantico.setColorText(new java.awt.Color(0, 51, 102));
        btnSemantico.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnSemantico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSemantico.setIconTextGap(15);
        btnSemantico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-86-document-list (3).png"))); // NOI18N
        btnSemantico.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-86-document-list.png"))); // NOI18N
        btnSemantico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemanticoActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnSemantico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 290, -1));

        btnIntermedio.setBackground(new java.awt.Color(162, 217, 245));
        btnIntermedio.setForeground(new java.awt.Color(0, 102, 102));
        btnIntermedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-70-document-code.png"))); // NOI18N
        btnIntermedio.setText("Código intermedio");
        btnIntermedio.setColorHover(new java.awt.Color(255, 255, 255));
        btnIntermedio.setColorText(new java.awt.Color(0, 51, 102));
        btnIntermedio.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnIntermedio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIntermedio.setIconTextGap(15);
        btnIntermedio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-70-document-code (3).png"))); // NOI18N
        btnIntermedio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-70-document-code.png"))); // NOI18N
        btnIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntermedioActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 290, -1));

        btnOptimizado.setBackground(new java.awt.Color(162, 217, 245));
        btnOptimizado.setForeground(new java.awt.Color(0, 102, 102));
        btnOptimizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-90-inbox-document.png"))); // NOI18N
        btnOptimizado.setText("Código optimizado");
        btnOptimizado.setColorHover(new java.awt.Color(255, 255, 255));
        btnOptimizado.setColorText(new java.awt.Color(0, 51, 102));
        btnOptimizado.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnOptimizado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOptimizado.setIconTextGap(15);
        btnOptimizado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-90-inbox-document (3).png"))); // NOI18N
        btnOptimizado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-90-inbox-document.png"))); // NOI18N
        btnOptimizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptimizadoActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnOptimizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 290, -1));

        btnAbrir.setBackground(new java.awt.Color(162, 217, 245));
        btnAbrir.setForeground(new java.awt.Color(0, 102, 102));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-58-document-upload.png"))); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setColorHover(new java.awt.Color(255, 255, 255));
        btnAbrir.setColorText(new java.awt.Color(0, 51, 102));
        btnAbrir.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnAbrir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbrir.setIconTextGap(15);
        btnAbrir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-58-document-upload (3).png"))); // NOI18N
        btnAbrir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-58-document-upload.png"))); // NOI18N
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, -1));

        btnObjeto.setBackground(new java.awt.Color(162, 217, 245));
        btnObjeto.setForeground(new java.awt.Color(0, 102, 102));
        btnObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-91-inbox-document-text.png"))); // NOI18N
        btnObjeto.setText("Código objeto");
        btnObjeto.setColorHover(new java.awt.Color(255, 255, 255));
        btnObjeto.setColorText(new java.awt.Color(0, 51, 102));
        btnObjeto.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnObjeto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnObjeto.setIconTextGap(15);
        btnObjeto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-91-inbox-document-text (3).png"))); // NOI18N
        btnObjeto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-91-inbox-document-text.png"))); // NOI18N
        panelNavegacion.add(btnObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, -1));

        btnAcerca.setBackground(new java.awt.Color(162, 217, 245));
        btnAcerca.setForeground(new java.awt.Color(0, 102, 102));
        btnAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-29-information_2.png"))); // NOI18N
        btnAcerca.setText("Acerca de");
        btnAcerca.setColorHover(new java.awt.Color(255, 255, 255));
        btnAcerca.setColorText(new java.awt.Color(0, 51, 102));
        btnAcerca.setColorTextHover(new java.awt.Color(0, 153, 204));
        btnAcerca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAcerca.setIconTextGap(15);
        btnAcerca.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-29-information_3.png"))); // NOI18N
        btnAcerca.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-29-information_2.png"))); // NOI18N
        btnAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 290, -1));

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tabEdicion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabEdicionStateChanged(evt);
            }
        });
        jSplitPane1.setTopComponent(tabEdicion);

        editorPaneSalida.setEditable(false);
        editorPaneSalida.setBackground(new java.awt.Color(0, 0, 0));
        editorPaneSalida.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        editorPaneSalida.setForeground(new java.awt.Color(153, 153, 153));
        editorPaneSalida.setText("run: ");
        editorPaneSalida.setMargin(new java.awt.Insets(6, 6, 6, 6));
        jScrollPane1.setViewportView(editorPaneSalida);

        tabSalida.addTab("Salida (run)", jScrollPane1);

        jSplitPane1.setRightComponent(tabSalida);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNavegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
//        Main.btnCargarArchivos();
        abrirVentanaAbrir();
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (tabEdicion.getTabCount() == 0) {
            Mensaje.error(this, "No hay nada para guardar");
        } else {
            if (tabEdicion.getSelectedIndex() != -1) {
                Main.btnGuardar();
            } else if (tabEdicion.getTabCount() == 1) {
                int index = 0;
                javax.swing.JScrollPane scroll = (javax.swing.JScrollPane) VtnCompilador.tabEdicion.getComponentAt(index);
                JViewport view = scroll.getViewport();
                javax.swing.JEditorPane edit = (javax.swing.JEditorPane) view.getView();
                Main.textoFuente = edit.getText();
                Main.btnGuardar();
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        if (tabEdicion.getSelectedIndex() != -1) {
            if (!Main.vtnResultado.isVisible()) {
                Main.vtnResultado.setVisible(true);
            }
            Main.btnLimpiar();
            Main.ResAnalisiLexico = "";
            Main.ResAnalisiSemantico = "";
            Main.ResAnalisiSintactico = "";
            Main.ResCodigoIntermedio = "";
            Main.ResCodigoOptimizado = "";
            Main.ResFuente = "";
            Main.ResOptimizacion = "";
            Main.textoFuente = "";

        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        if (!Main.vtnResultado.isVisible()) {
            Main.vtnResultado.setVisible(true);

            Main.ResAnalisiLexico = "";
            Main.ResAnalisiSemantico = "";
            Main.ResAnalisiSintactico = "";
            Main.ResCodigoIntermedio = "";
            Main.ResCodigoOptimizado = "";
            Main.ResFuente = "";
            Main.ResOptimizacion = "";

        }
        if (tabEdicion.getTabCount() == 0) {
            Mensaje.error(this, "No hay nada para compilar");
        } else {
            if (tabEdicion.getTabCount() == 1) {
                int index = 0;
                javax.swing.JScrollPane scroll = (javax.swing.JScrollPane) VtnCompilador.tabEdicion.getComponentAt(index);
                JViewport view = scroll.getViewport();
                javax.swing.JEditorPane edit = (javax.swing.JEditorPane) view.getView();
                Main.textoFuente = edit.getText();
                if (Main.textoFuente.isEmpty()) {
                    Mensaje.error(this, "Archivo vacio");
                } else {
                    Main.btnCompilar();
                }
            } else if (tabEdicion.getSelectedIndex() != -1) {
                int index = tabEdicion.getSelectedIndex();
                javax.swing.JScrollPane scroll = (javax.swing.JScrollPane) VtnCompilador.tabEdicion.getComponentAt(index);
                JViewport view = scroll.getViewport();
                javax.swing.JEditorPane edit = (javax.swing.JEditorPane) view.getView();
                Main.textoFuente = edit.getText();
                if (Main.textoFuente.isEmpty()) {
                    Mensaje.error(this, "Archivo vacio");
                } else {
                    Main.btnCompilar();
                }
            }
        }
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void btnLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexicoActionPerformed
        if (!Main.vtnResultado.isVisible()) {
            Main.vtnResultado.setVisible(true);
        }
        if (tabEdicion.getTabCount() == 0) {
            Mensaje.error(this, "No hay nada para compilar");
        } else {
            Main.btnLexico();
        }
    }//GEN-LAST:event_btnLexicoActionPerformed

    private void btnSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSintacticoActionPerformed
        if (!Main.vtnResultado.isVisible()) {
            Main.vtnResultado.setVisible(true);
        }
        if (tabEdicion.getTabCount() == 0) {
            Mensaje.error(this, "No hay nada para compilar");
        } else {
            Main.btnSintactico();
        }
    }//GEN-LAST:event_btnSintacticoActionPerformed

    private void btnSemanticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemanticoActionPerformed
        if (!Main.vtnResultado.isVisible()) {
            Main.vtnResultado.setVisible(true);
        }
        if (tabEdicion.getTabCount() == 0) {
            Mensaje.error(this, "No hay nada para compilar");
        } else {
            Main.btnSematico();
        }

    }//GEN-LAST:event_btnSemanticoActionPerformed

    private void btnIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntermedioActionPerformed
        if (!Main.vtnResultado.isVisible()) {
            Main.vtnResultado.setVisible(true);
        }
        if (tabEdicion.getTabCount() == 0) {
            Mensaje.error(this, "No hay nada para compilar");
        } else {
            Main.btnIntermedio();
        }
    }//GEN-LAST:event_btnIntermedioActionPerformed

    private void btnOptimizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptimizadoActionPerformed
        if (!Main.vtnResultado.isVisible()) {
            Main.vtnResultado.setVisible(true);
        }
        if (tabEdicion.getTabCount() == 0) {
            Mensaje.error(this, "No hay nada para compilar");
        } else {
            Main.btnOptimizacion();
        }
    }//GEN-LAST:event_btnOptimizadoActionPerformed

    private void btnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaActionPerformed
        VtnAcercaDe vtnAcercaDe = new VtnAcercaDe(this, false);
        vtnAcercaDe.setVisible(true);
    }//GEN-LAST:event_btnAcercaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        abrirVentanaGuardar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tabEdicionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabEdicionStateChanged

        if (tabEdicion.getSelectedIndex() != -1) {
            int index = VtnCompilador.tabEdicion.getSelectedIndex();
            javax.swing.JScrollPane scroll = (javax.swing.JScrollPane) VtnCompilador.tabEdicion.getComponentAt(index);
            JViewport view = scroll.getViewport();
            javax.swing.JEditorPane edit = (javax.swing.JEditorPane) view.getView();
            Main.textoFuente = edit.getText();
        } else if (tabEdicion.getTabCount() == 1) {
            int index = 0;
            javax.swing.JScrollPane scroll = (javax.swing.JScrollPane) VtnCompilador.tabEdicion.getComponentAt(index);
            JViewport view = scroll.getViewport();
            javax.swing.JEditorPane edit = (javax.swing.JEditorPane) view.getView();
            Main.textoFuente = edit.getText();
        } else {
            Main.textoFuente = "";
        }


    }//GEN-LAST:event_tabEdicionStateChanged

    private void btnDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentacionActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        new VtnDocumentacion().setVisible(true);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_btnDocumentacionActionPerformed

    public void abrirVentanaAbrir() {
        JFileChooser selecciona = new JFileChooser();  //crea objeto file chooser
        selecciona.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        //  FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo .txt", "txt", "txt");  //solo muestra archivos .mp3 en file chocer
        //  selecciona.setFileFilter(filtro);  //se agrega el filtro al file chooser
        selecciona.showOpenDialog(this);   //sin esto me marcaba error :v
        File archivoExtraido = selecciona.getSelectedFile(); //obtiene el archivo en la variable archivo
        String url; //borra la ruta para evitar que se quede una anterior
        String etiquetaNombre;
        if (archivoExtraido != null) // si no se selecciono ningun archivo no hace nada
        {
            if (archivoExtraido.isFile()) {
                try {
                    url = archivoExtraido.getCanonicalPath(); //obtiene la ruta del archivo
                    etiquetaNombre = archivoExtraido.getName();//obtiene el nombre del archivo/cancion
                    String texto = ManipulaArchivos.cargarArchivo(url);
                    boolean repetidos = false;
                    for (int i = 0; i < Main.archivos.size(); i++) {
                        if (Main.archivos.get(i).getNombre().equals(etiquetaNombre)) {
                            repetidos = true;
                            break;
                        }
                    }
                    if (repetidos) {
                        Mensaje.error(this, "Ya existe un archivo abierto con el mismo nombre");
                    } else {
                        Main.abrirArchivo(tabEdicion, etiquetaNombre, texto, url);
                    }

                } catch (IOException ex) {
                    TextPaneTest.appendToPane((JTextPane) editorPaneSalida, "Ups! Ha ocurrido un error " + ex.toString(), Color.red);
                }

            } else {
            }
        }

    }

    public void abrirVentanaGuardar() {
        JFileChooser selecciona = new JFileChooser();  //crea objeto file chooser
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo .txt", "txt", "txt");  //solo muestra archivos .mp3 en file chocer
        selecciona.setFileFilter(filtro);  //se agrega el filtro al file chooser
        selecciona.showSaveDialog(this);
        File archivoNuevo = selecciona.getSelectedFile(); //obtiene el archivo en la variable archivo
        String url; //borra la ruta para evitar que se quede una anterior
        String etiquetaNombre;

        if (archivoNuevo != null) // si no se selecciono ningun archivo no hace nada
        {
            try {
                url = archivoNuevo.getCanonicalPath(); //obtiene la ruta del archivo
                etiquetaNombre = archivoNuevo.getName();//obtiene el nombre del archivo
                Main.nuevoArchivo(VtnCompilador.tabEdicion, etiquetaNombre, url);
                ManipulaArchivos.crearNuevo(url);
            } catch (IOException ex) {
                TextPaneTest.appendToPane((JTextPane) editorPaneSalida, "Ups! Ha ocurrido un error " + ex.toString(), Color.red);
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            TextPaneTest.appendToPane((JTextPane) editorPaneSalida, "Ups! Ha ocurrido un error " + ex.toString(), Color.red);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VtnCompilador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnAbrir;
    private rojeru_san.RSButton btnAcerca;
    private rojeru_san.RSButton btnCompilar;
    private rojeru_san.RSButton btnDocumentacion;
    private rojeru_san.RSButton btnGuardar;
    private rojeru_san.RSButton btnIntermedio;
    private rojeru_san.RSButton btnLexico;
    private rojeru_san.RSButton btnLimpiar;
    private rojeru_san.RSButton btnNuevo;
    private rojeru_san.RSButton btnObjeto;
    private rojeru_san.RSButton btnOptimizado;
    private rojeru_san.RSButton btnSemantico;
    private rojeru_san.RSButton btnSintactico;
    public static javax.swing.JTextPane editorPaneSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel panelNavegacion;
    private javax.swing.JPanel panelPrincipal;
    public static javax.swing.JTabbedPane tabEdicion;
    public static javax.swing.JTabbedPane tabSalida;
    // End of variables declaration//GEN-END:variables
}
