/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import recursos.CambiaPanel;

/**
 *
 * @author Kevin_Sanchez
 */
public class VtnResultadoCmp extends javax.swing.JFrame {

    private final ImageIcon imageLenguaje1 = new ImageIcon(ClassLoader.getSystemResource("imagenes/edicion.png"));
    private final ImageIcon imageLenguaje2 = new ImageIcon(ClassLoader.getSystemResource("imagenes/salida.png"));

    /**
     * Creates new form VtnCompilador
     */
    public VtnResultadoCmp() {
        initComponents();
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/proyecto.png"));
        this.setIconImage(icono);
        setTitle("Resultados de la compilación");
        setLocationRelativeTo(null);
        btnAanlisis.setSelected(true);
        CambiaPanel cambiaPanel = new CambiaPanel(jPanel2, new PnlAnalisis());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelNavegacion = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOptimizacion = new javax.swing.JToggleButton();
        btnAanlisis = new javax.swing.JToggleButton();
        btnTablaSimbol = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compilador");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1456, 850));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelNavegacion.setBackground(new java.awt.Color(162, 217, 245));
        panelNavegacion.setPreferredSize(new java.awt.Dimension(1436, 900));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proyecto (3).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Compilador");

        btnOptimizacion.setBackground(new java.awt.Color(0, 51, 102));
        buttonGroup1.add(btnOptimizacion);
        btnOptimizacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnOptimizacion.setForeground(new java.awt.Color(255, 255, 255));
        btnOptimizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-73-documents (2).png"))); // NOI18N
        btnOptimizacion.setText("Codigo optimizado");
        btnOptimizacion.setContentAreaFilled(false);
        btnOptimizacion.setIconTextGap(10);
        btnOptimizacion.setOpaque(true);
        btnOptimizacion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-73-documents.png"))); // NOI18N
        btnOptimizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptimizacionActionPerformed(evt);
            }
        });

        btnAanlisis.setBackground(new java.awt.Color(0, 51, 102));
        buttonGroup1.add(btnAanlisis);
        btnAanlisis.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAanlisis.setForeground(new java.awt.Color(255, 255, 255));
        btnAanlisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-74-document-search (2).png"))); // NOI18N
        btnAanlisis.setText("Ánalisis");
        btnAanlisis.setContentAreaFilled(false);
        btnAanlisis.setIconTextGap(10);
        btnAanlisis.setOpaque(true);
        btnAanlisis.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-74-document-search.png"))); // NOI18N
        btnAanlisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAanlisisActionPerformed(evt);
            }
        });

        btnTablaSimbol.setBackground(new java.awt.Color(0, 51, 102));
        buttonGroup1.add(btnTablaSimbol);
        btnTablaSimbol.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTablaSimbol.setForeground(new java.awt.Color(255, 255, 255));
        btnTablaSimbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-62-document-table (2).png"))); // NOI18N
        btnTablaSimbol.setText("Tabla de simbolos");
        btnTablaSimbol.setContentAreaFilled(false);
        btnTablaSimbol.setIconTextGap(10);
        btnTablaSimbol.setOpaque(true);
        btnTablaSimbol.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-62-document-table.png"))); // NOI18N
        btnTablaSimbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaSimbolActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBorder(null);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(162, 217, 245));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane2.setViewportView(jPanel2);

        jPanel1.add(jScrollPane2);

        javax.swing.GroupLayout panelNavegacionLayout = new javax.swing.GroupLayout(panelNavegacion);
        panelNavegacion.setLayout(panelNavegacionLayout);
        panelNavegacionLayout.setHorizontalGroup(
            panelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(btnAanlisis, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTablaSimbol, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOptimizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelNavegacionLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        panelNavegacionLayout.setVerticalGroup(
            panelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavegacionLayout.createSequentialGroup()
                .addGroup(panelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelNavegacionLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAanlisis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTablaSimbol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOptimizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavegacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelNavegacion);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAanlisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAanlisisActionPerformed
        CambiaPanel cambiaPanel = new CambiaPanel(jPanel2, new PnlAnalisis());
    }//GEN-LAST:event_btnAanlisisActionPerformed

    private void btnTablaSimbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaSimbolActionPerformed
        CambiaPanel cambiaPanel = new CambiaPanel(jPanel2, new PnlTablaSimbolos());
    }//GEN-LAST:event_btnTablaSimbolActionPerformed

    private void btnOptimizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptimizacionActionPerformed
        CambiaPanel cambiaPanel = new CambiaPanel(jPanel2, new PnlCodigoOptimizado());
    }//GEN-LAST:event_btnOptimizacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnResultadoCmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnResultadoCmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnResultadoCmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnResultadoCmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnResultadoCmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAanlisis;
    private javax.swing.JToggleButton btnOptimizacion;
    private javax.swing.JToggleButton btnTablaSimbol;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel panelNavegacion;
    // End of variables declaration//GEN-END:variables
}
